"""Fail-closed capability checks and short-lived motion authorization."""

from .faults import FaultCode
from .interlocks import HealthState, InterlockSnapshot
from .permit import (
    FeedbackPermit,
    FeedbackPermitError,
    MotionPermit,
    MotionPermitError,
    goal_hash,
)
from .preflight import PreflightCheck, PreflightReport, RuntimeStatus, evaluate_preflight
from .state_machine import SafetyState, SafetyStateMachine, StateTransitionError
from .supervisor import AuthorizationError, SafetySupervisor
from .authorization_v2 import (
    AUTHORIZATION_V2_SCHEMA,
    CALIBRATION_CLOSURE_SCHEMA,
    KEYBOARD_REQUIRED_ARTIFACT_IDS,
    PHONE_REQUIRED_ARTIFACT_IDS,
    SIMULATION_PERMIT_SCHEMA,
    SIMULATION_RECEIPT_SCHEMA,
    TRAJECTORY_SEQUENCE_SCHEMA,
    ZERO_AUTHORITY,
    AuthorizationContinuityEvidence,
    AuthorizationEvidence,
    AuthorizationV2Error,
    BuildReleaseIdentity,
    CalibrationArtifactBinding,
    CalibrationClosureEvidence,
    CollisionClearanceState,
    CollisionTrajectoryEvidence,
    ControllerSessionEvidence,
    EvidenceOnlyReleaseScope,
    InterlockChannel,
    InterlockChannelEvidence,
    InterlockEvidenceBundle,
    InterlockEvidenceState,
    NamedSha256,
    OperatorArmEvidence,
    OrderedSimulationPermit,
    SimulatedContactCapability,
    SimulationCommandReceipt,
    SimulationPrimitive,
    SimulationTrajectoryCommand,
    calibration_closure_from_registry,
    canonical_record_sha256,
    continuity_from_authorization,
    issue_ordered_simulation_permit,
    trajectory_sequence_sha256,
)

__all__ = [
    "AuthorizationError",
    "AUTHORIZATION_V2_SCHEMA",
    "CALIBRATION_CLOSURE_SCHEMA",
    "KEYBOARD_REQUIRED_ARTIFACT_IDS",
    "PHONE_REQUIRED_ARTIFACT_IDS",
    "SIMULATION_PERMIT_SCHEMA",
    "SIMULATION_RECEIPT_SCHEMA",
    "TRAJECTORY_SEQUENCE_SCHEMA",
    "ZERO_AUTHORITY",
    "AuthorizationContinuityEvidence",
    "AuthorizationEvidence",
    "AuthorizationV2Error",
    "BuildReleaseIdentity",
    "CalibrationArtifactBinding",
    "CalibrationClosureEvidence",
    "CollisionClearanceState",
    "CollisionTrajectoryEvidence",
    "ControllerSessionEvidence",
    "EvidenceOnlyReleaseScope",
    "InterlockChannel",
    "InterlockChannelEvidence",
    "InterlockEvidenceState",
    "InterlockEvidenceBundle",
    "NamedSha256",
    "OperatorArmEvidence",
    "OrderedSimulationPermit",
    "SimulatedContactCapability",
    "SimulationCommandReceipt",
    "SimulationPrimitive",
    "SimulationTrajectoryCommand",
    "calibration_closure_from_registry",
    "canonical_record_sha256",
    "continuity_from_authorization",
    "issue_ordered_simulation_permit",
    "trajectory_sequence_sha256",
    "FaultCode",
    "FeedbackPermit",
    "FeedbackPermitError",
    "HealthState",
    "InterlockSnapshot",
    "MotionPermit",
    "MotionPermitError",
    "PreflightCheck",
    "PreflightReport",
    "RuntimeStatus",
    "SafetyState",
    "SafetyStateMachine",
    "SafetySupervisor",
    "StateTransitionError",
    "evaluate_preflight",
    "goal_hash",
]
