"""Stable, machine-readable preflight and runtime fault codes."""

from __future__ import annotations

from enum import Enum


class FaultCode(str, Enum):
    CAPABILITY_DENIED = "CAPABILITY_DENIED"
    ACTIVE_BUILD_MISSING = "ACTIVE_BUILD_MISSING"
    ROBOT_POWER_NOT_RELEASED = "ROBOT_POWER_NOT_RELEASED"
    CONTACT_DISABLED = "CONTACT_DISABLED"
    CALIBRATION_INVALID = "CALIBRATION_INVALID"
    INTERLOCK_STALE = "INTERLOCK_STALE"
    ESTOP_CHAIN_UNHEALTHY = "ESTOP_CHAIN_UNHEALTHY"
    BOARD_ANTI_SHIFT_UNHEALTHY = "BOARD_ANTI_SHIFT_UNHEALTHY"
    GRAVITY_CONTAINMENT_UNHEALTHY = "GRAVITY_CONTAINMENT_UNHEALTHY"
    CONTACT_GUARD_UNHEALTHY = "CONTACT_GUARD_UNHEALTHY"
    ARM_NOT_CONNECTED = "ARM_NOT_CONNECTED"
    ARM_FEEDBACK_STALE = "ARM_FEEDBACK_STALE"
    CAMERA_UNAVAILABLE = "CAMERA_UNAVAILABLE"
    CAMERA_UNQUALIFIED = "CAMERA_UNQUALIFIED"
    PATH_NOT_CLEARED = "PATH_NOT_CLEARED"
    DEVICE_NOT_VERIFIED = "DEVICE_NOT_VERIFIED"
    OPERATOR_NOT_ARMED = "OPERATOR_NOT_ARMED"
    STATE_TRANSITION_INVALID = "STATE_TRANSITION_INVALID"
    PERMIT_EXPIRED = "PERMIT_EXPIRED"
    PERMIT_REVOKED = "PERMIT_REVOKED"
    GOAL_NOT_AUTHORIZED = "GOAL_NOT_AUTHORIZED"
