"""Versioned, dependency-aware calibration artifacts."""

from .artifacts import (
    ArtifactAssessment,
    ArtifactState,
    CalibrationArtifact,
    CalibrationResolution,
)
from .eye_on_arm_dataset import (
    EQUATION as EYE_ON_ARM_EQUATION,
    JOINT_ORDER as EYE_ON_ARM_JOINT_ORDER,
    MAX_DATASET_BYTES as EYE_ON_ARM_MAX_DATASET_BYTES,
    REQUIRED_SOURCE_HASHES as EYE_ON_ARM_REQUIRED_SOURCE_HASHES,
    CarrierPoseRecord,
    EyeOnArmCameraBinding,
    EyeOnArmDataset,
    EyeOnArmDatasetError,
    EyeOnArmSample,
    ImageRecord,
    JointStateRecord,
    SynchronizationPolicy,
    TargetPoseRecord,
    eye_on_arm_dataset_from_dict,
    load_eye_on_arm_dataset,
)
from .eye_on_arm_capture_bundle import (
    CAPTURE_BUNDLE_PHYSICAL_BLOCKERS,
    DEFAULT_CAPTURE_BUNDLE_POLICY,
    MAX_BUNDLE_FILE_BYTES as EYE_ON_ARM_MAX_CAPTURE_BUNDLE_BYTES,
    CaptureBundleSample,
    CaptureBundleSampleVerification,
    CaptureBundleVerificationPolicy,
    EyeOnArmCaptureBundle,
    EyeOnArmCaptureBundleError,
    EyeOnArmCaptureBundleVerification,
    FeedbackWireObservation,
    NormalizedDetectionEvidence,
    assemble_eye_on_arm_capture_bundle,
    eye_on_arm_capture_bundle_from_dict,
    load_eye_on_arm_capture_bundle,
    verify_eye_on_arm_capture_bundle,
)
from .eye_on_arm_evidence import (
    DEFAULT_FK_VERIFICATION_POLICY,
    PINNED_ROARM_M3_KINEMATIC_SHA256,
    EyeOnArmCaptureEvidence,
    EyeOnArmEvidenceError,
    EyeOnArmFkVerification,
    EyeOnArmFkVerificationPolicy,
    FkSampleVerification,
    JointReferenceRule,
    RawJointFeedbackEvidence,
    eye_on_arm_capture_evidence_from_dict,
    load_eye_on_arm_capture_evidence,
    verify_eye_on_arm_fk,
)
from .eye_on_arm_commissioning import (
    DEFAULT_COMMISSIONING_POLICY,
    CommissioningCheck,
    EyeOnArmCommissioningAssessment,
    EyeOnArmCommissioningContext,
    EyeOnArmCommissioningPolicy,
    assess_eye_on_arm_commissioning,
)
from .eye_on_arm_solver import (
    DEFAULT_EYE_ON_ARM_SOLVER_POLICY,
    EyeOnArmObservability,
    EyeOnArmSolveError,
    EyeOnArmSolveResult,
    EyeOnArmSolverUnavailable,
    EyeOnArmSolverPolicy,
    PoseResidual,
    ResidualSummary,
    solve_eye_on_arm,
)
from .registry import CalibrationRegistry, CalibrationRegistryError
from .requirements import (
    REQUIREMENTS,
    CalibrationRequirement,
    ordered_requirement_closure,
)
from .static_phase1_requirements import (
    STATIC_OVERHEAD_PHASE1_AUTHORITY,
    STATIC_OVERHEAD_PHASE1_DEVICE_TERMINALS,
    STATIC_OVERHEAD_PHASE1_GRAPH,
    STATIC_OVERHEAD_PHASE1_GRAPH_ID,
    STATIC_OVERHEAD_PHASE1_GRAPH_SCHEMA,
    STATIC_OVERHEAD_PHASE1_REQUIREMENTS,
    StaticPhase1CalibrationGraph,
    StaticPhase1CalibrationRequirement,
    StaticPhase1RequirementError,
    ordered_static_phase1_requirement_closure,
)
from .static_camera_intrinsics import (
    MAX_INTRINSICS_IMAGES,
    MAX_STATIC_CAMERA_INTRINSICS_BYTES,
    STATIC_CAMERA_INTRINSICS_ASSESSMENT_SCHEMA,
    STATIC_CAMERA_INTRINSICS_SCHEMA,
    TARGET_PROFILE_ID as STATIC_INTRINSICS_TARGET_PROFILE_ID,
    TARGET_PROFILE_SOURCE_SHA256 as STATIC_INTRINSICS_TARGET_PROFILE_SOURCE_SHA256,
    CharucoBoardDefinition,
    IntrinsicsImageObservation,
    IntrinsicsViewResidual,
    StaticCameraIntrinsicsAssessment,
    StaticCameraIntrinsicsError,
    StaticCameraIntrinsicsRehearsal,
    StaticIntrinsicsMode,
    assess_static_camera_intrinsics_rehearsal,
    load_static_camera_intrinsics_rehearsal,
    parse_static_camera_intrinsics_json,
)

__all__ = [
    "ArtifactAssessment",
    "ArtifactState",
    "CalibrationRequirement",
    "CalibrationArtifact",
    "CalibrationRegistry",
    "CalibrationRegistryError",
    "CalibrationResolution",
    "CarrierPoseRecord",
    "CAPTURE_BUNDLE_PHYSICAL_BLOCKERS",
    "CaptureBundleSample",
    "CaptureBundleSampleVerification",
    "CaptureBundleVerificationPolicy",
    "CommissioningCheck",
    "DEFAULT_CAPTURE_BUNDLE_POLICY",
    "DEFAULT_COMMISSIONING_POLICY",
    "DEFAULT_FK_VERIFICATION_POLICY",
    "DEFAULT_EYE_ON_ARM_SOLVER_POLICY",
    "EYE_ON_ARM_EQUATION",
    "EYE_ON_ARM_MAX_CAPTURE_BUNDLE_BYTES",
    "EYE_ON_ARM_JOINT_ORDER",
    "EYE_ON_ARM_MAX_DATASET_BYTES",
    "EYE_ON_ARM_REQUIRED_SOURCE_HASHES",
    "EyeOnArmCameraBinding",
    "EyeOnArmCaptureBundle",
    "EyeOnArmCaptureBundleError",
    "EyeOnArmCaptureBundleVerification",
    "EyeOnArmCaptureEvidence",
    "EyeOnArmCommissioningAssessment",
    "EyeOnArmCommissioningContext",
    "EyeOnArmCommissioningPolicy",
    "EyeOnArmDataset",
    "EyeOnArmDatasetError",
    "EyeOnArmObservability",
    "EyeOnArmEvidenceError",
    "EyeOnArmFkVerification",
    "EyeOnArmFkVerificationPolicy",
    "EyeOnArmSample",
    "EyeOnArmSolveError",
    "EyeOnArmSolveResult",
    "EyeOnArmSolverUnavailable",
    "EyeOnArmSolverPolicy",
    "ImageRecord",
    "IntrinsicsImageObservation",
    "IntrinsicsViewResidual",
    "JointStateRecord",
    "JointReferenceRule",
    "PoseResidual",
    "PINNED_ROARM_M3_KINEMATIC_SHA256",
    "REQUIREMENTS",
    "ResidualSummary",
    "RawJointFeedbackEvidence",
    "SynchronizationPolicy",
    "STATIC_CAMERA_INTRINSICS_ASSESSMENT_SCHEMA",
    "STATIC_CAMERA_INTRINSICS_SCHEMA",
    "STATIC_INTRINSICS_TARGET_PROFILE_ID",
    "STATIC_INTRINSICS_TARGET_PROFILE_SOURCE_SHA256",
    "STATIC_OVERHEAD_PHASE1_AUTHORITY",
    "STATIC_OVERHEAD_PHASE1_DEVICE_TERMINALS",
    "STATIC_OVERHEAD_PHASE1_GRAPH",
    "STATIC_OVERHEAD_PHASE1_GRAPH_ID",
    "STATIC_OVERHEAD_PHASE1_GRAPH_SCHEMA",
    "STATIC_OVERHEAD_PHASE1_REQUIREMENTS",
    "StaticCameraIntrinsicsAssessment",
    "StaticCameraIntrinsicsError",
    "StaticCameraIntrinsicsRehearsal",
    "StaticIntrinsicsMode",
    "StaticPhase1CalibrationGraph",
    "StaticPhase1CalibrationRequirement",
    "StaticPhase1RequirementError",
    "TargetPoseRecord",
    "FkSampleVerification",
    "FeedbackWireObservation",
    "NormalizedDetectionEvidence",
    "assemble_eye_on_arm_capture_bundle",
    "assess_static_camera_intrinsics_rehearsal",
    "assess_eye_on_arm_commissioning",
    "eye_on_arm_capture_bundle_from_dict",
    "eye_on_arm_capture_evidence_from_dict",
    "eye_on_arm_dataset_from_dict",
    "load_eye_on_arm_dataset",
    "load_eye_on_arm_capture_evidence",
    "load_eye_on_arm_capture_bundle",
    "load_static_camera_intrinsics_rehearsal",
    "MAX_INTRINSICS_IMAGES",
    "MAX_STATIC_CAMERA_INTRINSICS_BYTES",
    "ordered_requirement_closure",
    "ordered_static_phase1_requirement_closure",
    "parse_static_camera_intrinsics_json",
    "solve_eye_on_arm",
    "verify_eye_on_arm_fk",
    "verify_eye_on_arm_capture_bundle",
    "CharucoBoardDefinition",
]
