"""Immutable, bounded evidence packages for hardware-free commissioning."""

from .virtual_session import (
    VerifiedVirtualSessionRecord,
    VirtualSessionEvidenceError,
    VirtualSessionRecord,
    VirtualSessionReplayReport,
    record_virtual_session,
    replay_virtual_session,
    verify_virtual_session_record,
)
from .prehardware_qualification import (
    CASES_ARTIFACT_SCHEMA,
    COVERAGE_ARTIFACT_SCHEMA,
    MANIFEST_SCHEMA as PREHARDWARE_QUALIFICATION_EVIDENCE_MANIFEST_SCHEMA,
    REPLAY_SCHEMA as PREHARDWARE_QUALIFICATION_REPLAY_SCHEMA,
    RESOURCES_ARTIFACT_SCHEMA,
    SOURCE_ARTIFACT_SCHEMA,
    PrehardwareQualificationEvidenceError,
    PrehardwareQualificationEvidenceRecord,
    PrehardwareQualificationReplayReport,
    VerifiedPrehardwareQualificationEvidence,
    record_prehardware_qualification,
    replay_prehardware_qualification,
    verify_prehardware_qualification_record,
)
from .sensor_session import (
    CAMERA_SCHEMA as RAW_SENSOR_SESSION_CAMERA_SCHEMA,
    CONTENT_SCHEMA as RAW_SENSOR_SESSION_CONTENT_SCHEMA,
    CONTRACT_SCHEMA as RAW_SENSOR_SESSION_CONTRACT_SCHEMA,
    MANIFEST_SCHEMA as RAW_SENSOR_SESSION_MANIFEST_SCHEMA,
    PERCEPTION_SCHEMA as RAW_SENSOR_SESSION_PERCEPTION_SCHEMA,
    PIXEL_LAYOUT_SCHEMA as RAW_SENSOR_SESSION_PIXEL_LAYOUT_SCHEMA,
    REPLAY_SCHEMA as RAW_SENSOR_SESSION_REPLAY_SCHEMA,
    TIMING_SCHEMA as RAW_SENSOR_SESSION_TIMING_SCHEMA,
    CameraControlSnapshot,
    CameraModeSnapshot,
    FramePixelLayouts,
    PixelBufferLayout,
    RawSensorSessionInput,
    ReplayedSensorSession,
    SensorSessionContract,
    SensorSessionEvidenceError,
    SensorSessionRecord,
    SensorTimingBracket,
    SyntheticCameraIdentity,
    VerifiedSensorSessionRecord,
    record_sensor_session,
    replay_sensor_session,
    verify_sensor_session_record,
)

__all__ = [
    "VerifiedVirtualSessionRecord",
    "VirtualSessionEvidenceError",
    "VirtualSessionRecord",
    "VirtualSessionReplayReport",
    "record_virtual_session",
    "replay_virtual_session",
    "verify_virtual_session_record",
    "PREHARDWARE_QUALIFICATION_EVIDENCE_MANIFEST_SCHEMA",
    "PREHARDWARE_QUALIFICATION_REPLAY_SCHEMA",
    "SOURCE_ARTIFACT_SCHEMA",
    "CASES_ARTIFACT_SCHEMA",
    "COVERAGE_ARTIFACT_SCHEMA",
    "RESOURCES_ARTIFACT_SCHEMA",
    "PrehardwareQualificationEvidenceError",
    "PrehardwareQualificationEvidenceRecord",
    "PrehardwareQualificationReplayReport",
    "VerifiedPrehardwareQualificationEvidence",
    "record_prehardware_qualification",
    "replay_prehardware_qualification",
    "verify_prehardware_qualification_record",
    "RAW_SENSOR_SESSION_CAMERA_SCHEMA",
    "RAW_SENSOR_SESSION_CONTENT_SCHEMA",
    "RAW_SENSOR_SESSION_CONTRACT_SCHEMA",
    "RAW_SENSOR_SESSION_MANIFEST_SCHEMA",
    "RAW_SENSOR_SESSION_PERCEPTION_SCHEMA",
    "RAW_SENSOR_SESSION_PIXEL_LAYOUT_SCHEMA",
    "RAW_SENSOR_SESSION_REPLAY_SCHEMA",
    "RAW_SENSOR_SESSION_TIMING_SCHEMA",
    "CameraControlSnapshot",
    "CameraModeSnapshot",
    "FramePixelLayouts",
    "PixelBufferLayout",
    "RawSensorSessionInput",
    "ReplayedSensorSession",
    "SensorSessionContract",
    "SensorSessionEvidenceError",
    "SensorSessionRecord",
    "SensorTimingBracket",
    "SyntheticCameraIdentity",
    "VerifiedSensorSessionRecord",
    "record_sensor_session",
    "replay_sensor_session",
    "verify_sensor_session_record",
]
